name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Perform Checkout
      uses: actions/checkout@v1

    - name: Install Stuff
      run: |
        Install-Module Az -Force
        Install-Module Sporq -Force
        Install-Module Pester
      shell: pwsh

    - name: Log in to Azure using Service Principal
      run: |
        $passwd = ConvertTo-SecureString "${{ secrets.sporq_sp_client_secret }}" -AsPlainText -Force
        $pscredential = New-Object System.Management.Automation.PSCredential("c04a7026-3bdb-4643-8539-0c0f18d26b6f", $passwd)
        Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant "72f988bf-86f1-41af-91ab-2d7cd011db47"
      shell: pwsh

    - name: Emit and Test Arm Template
      run: |
        ./azuredeploy.ps1
        $parameters = @{ TemplatePath = $TemplatePath }
        # put that and a root location for where the tests are into the $script object
        $script = @{ Path = "."; Parameters = $parameters }
        Invoke-Pester -Script $script -OutputFile Tests.Report.xml -OutputFormat NUnitXml
      shell: pwsh

    - name: Deploy Arm Template
      run: |
        $date = Get-Date -Format FileDateTime
        New-AzResourceGroupDeployment -ResourceGroupName "test-sporq-rg" -TemplateFile "./azuredeploy.json" -Name $date
      shell: pwsh