name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Perform Checkout
      uses: actions/checkout@v1

    - name: Install Stuff
      run: |
        Install-Module Az -Force
        Install-Module Sporq -Force
      shell: pwsh

    - name: Log in to Azure using Service Principal
      run: |
        $passwd = ConvertTo-SecureString "${{ secrets.sporq_sp_client_secret }}" -AsPlainText -Force
        $pscredential = New-Object System.Management.Automation.PSCredential("c04a7026-3bdb-4643-8539-0c0f18d26b6f", $passwd)
        Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant "72f988bf-86f1-41af-91ab-2d7cd011db47"
      shell: pwsh

    - name: Emit and Deploy Arm Template
      run: |
        ./azuredeploy.ps1
        New-AzResourceGroupDeployment -ResourceGroupName "test-sporq-rg" -TemplateFile "./azuredeploy.json"
      shell: pwsh