name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Arm Template to Azure
      run: |
        ./azuredeploy.ps1
      shell: pwsh
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.sporq_deploy_creds }}
    
    - run: |
        az webapp list --query "[?state=='Running']"