name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Perform Checkout
      uses: actions/checkout@v1
    
    - name: Emit Arm Template
      run: |
        Install-Module Sporq -Force
        ./azuredeploy.ps1
      shell: pwsh
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.sporq_deploy_creds }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group deployment create --resource-group "test-sporq-rg" --template-file "./out/azuredeploy.json" --name test-deploy
