name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Emit Arm Template
      run: |
        Install-Module Sporq -Force
        ./azuredeploy.ps1
        Get-ChildItem
        Get-ChildItem ./out
      shell: pwsh
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.sporq_deploy_creds }}
    - run: |
        az group deployment create --resource-group "test-sporq-rg" --template-file ./out/azuredeploy.json
